### ISSUE TITLE
Add Manifest for NoMAD Login+

### ISSUE THREAD

**Issue by MartinLeedotOrg** [erikberglund/ProfileManifests#11]
Docs here:
https://files.nomad.menu/NoMADLoginPlusAdminGuide.pdf

I can pick this up at some point.

**Comment by erikberglund** [comment]
I will add this, thanks for the link.

**Comment by erikberglund** [comment]
I've uploaded a manifest for the `menu.nomad.login.okta` domain. So you just need to download it from within the application to get it. -> Preferences -> Payloads download if it's available, or else it have downloaded it automatically.

I am working on adding settings for the domain, as this probably changed it's domain to the new Jamf name. We'll see how I solve that in a good way.
