### ISSUE TITLE
MunkiReport

### ISSUE THREAD

**Issue by digitalhealer** [erikberglund/ProfileManifests#18]
Could you add a manifest for MunkiReport.  Documentation is below

https://github.com/munkireport/munkireport-php/wiki/Client-Configuration

**Comment by apizz** [comment]
I'll work on this.

**Comment by apizz** [comment]
@digitalhealer Added to my fork per [this commit](https://github.com/apizz/ProfileManifests/commit/61c4f60e837379f5a99effa8c3513b5ac7629679).

Working on some other additions ATM, so feel free to use the manifest from my fork until it's added to the main project.

**Comment by apizz** [comment]
Sorry for all the duplicate references ... I spent a lot of time trying to figure out how to get my previous commits separated out to different branches.

**Comment by apizz** [comment]
PR merge completed.
