### ISSUE TITLE
Date and Time Prefs

### ISSUE THREAD

**Issue by peteostro** [erikberglund/ProfileManifests#20]
Looking for profile settings for date & time: time zone, time server, clock settings. macOS

**Comment by apizz** [comment]
@peteostro these are controlled by the `com.apple.MCX` domain, which is the same as some Energy Settings and at least one other.

It wouldn't take much work to bring these all together, but there are some decisions about where this single, multi-purpose preference should live given it handles different aspects of the system.  This is discussed in [this issue](https://github.com/erikberglund/ProfileCreator/issues/79)

**Comment by peteostro** [comment]
ok. This is a big one, I think most places would like to set these settings. Thanks for your work

**Comment by apizz** [comment]
@peteostro Upcoming release will address this.  Doing some final testing with @erikberglund and will confirm these manifests are ready to go around the same time as the release

**Comment by apizz** [comment]
@peteostro this has been added in 0.2.5 release.
