### ISSUE TITLE
Add Education Configuration Payload (com.apple.education)

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileManifests#35]
Per https://developer.apple.com/business/documentation/Configuration-Profile-Reference.pdf

**Comment by AndyC-CMTC** [comment]
We would like to +1 this.  It would be really valuable for education users.

**Comment by jenis82** [comment]
+ 1, would rock my world!

**Comment by apizz** [comment]
At least once preference from the macOS Restrictions manifest (com.apple.applicationaccess-macOS) - `forceClassroomUnpromptedScreenObservation` requires a preference (`ScreenObservationPermissionModificationAllowed`) to be `true` from this yet uncreated Education payload.

Per https://github.com/erikberglund/ProfileManifests/commit/3c24c3aa4c35a14947ced9ff45f76473168bc754 I see the ability to reference a preference from another payload, but not sure if that would work for `pfm_exclude` or `pfm_conditionals`

**Comment by apizz** [comment]
@AndyC-CMTC & @jenis82 , the manifest is ready, but won't become available until 0.2.5 is released.

**Comment by jenis82** [comment]
Sweet! thanks ever so much

**Comment by apizz** [comment]
Added per https://github.com/erikberglund/ProfileManifests/pull/77
