### ISSUE TITLE
Update Microsoft Office (com.microsoft.autoupdate2)

### ISSUE THREAD

**Issue by qu1gl3s** [erikberglund/ProfileManifests#43]
Change Application ID from MSau03 to MSau04 as of version 4.7.1 of Microsoft AutoUpdate.

MSau03 for all versions prior to 4.7.1.

**Comment by qu1gl3s** [comment]
Changes pending under https://github.com/erikberglund/ProfileManifests/pull/52

**Comment by apizz** [comment]
Closed per #60
