### ISSUE TITLE
Loginwindow ChangePasswordDisabled not working?

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileManifests#62]
Recently for demo tried adding the `ChangePasswordDisabled` preference from the Login Window payload to a profile and it wasn't showing up under the Profiles pref pane when deployed via MDM.  Tried to confirm the existence of this preference in our MDM within the Login Window payload there, but didn't see it.

Know there's the ability to restrict access the the "Change Password" button in System Preferences, but my memory is failing me if this one-in-the-same, or different ...

Either way, despite exporting the profile and confirming it's presence in the created profile, the preference did not appear when deployed through MDM.

**Comment by erikberglund** [comment]
I just tried this manually and it worked as expected for me. 
[PasswordChange.mobileconfig.zip](https://github.com/erikberglund/ProfileManifests/files/3006678/PasswordChange.mobileconfig.zip)
![Skärmavbild 2019-03-26 kl  06 45 54](https://user-images.githubusercontent.com/1296345/54974032-d4788b00-4f92-11e9-90c7-4b62b6000dcb.png)

**Comment by erikberglund** [comment]
It uses the inverted boolean I believe, to match the description of Profile Manager maybe, if it's the wording that is confusing that is easy to change and to have the checkbox checked as the setting to disable the button. All of these inverted booleans are strange, but some places they make more sense than others.

**Comment by apizz** [comment]
@erikberglund wording isn't confusing to me.  When I installed the profile it just didn't lock down that particular preference.  I'll take another look and confirm

**Comment by apizz** [comment]
I see the pref in Jamf profiles, so this was just me ...
