### ISSUE TITLE
Applying separate policies for Google Chrome Stable and Beta versions

### ISSUE THREAD

**Issue by shashankshirke** [erikberglund/ProfileManifests#638]
### Please provide the following information:

**Name of App / Payload**: Google Chrome

**Preference key(s) needing fixing**: IncognitoModeAvailability

**Description of problem(s) / error(s) with listed key(s)**: I am unable to apply separate policies to different versions of Chrome using the com.google.Chrome.plist file.

**Description of expected behavior**:

I want to enforce Incognito mode (IncognitoModeAvailability = 2) on the stable Chrome release and keep other versions of Chrome (beta & dev) to enable normal browsing. I can enforce this policy on the stable Chrome version using the following com.google.Chrome.plist file put into /Library/Managed Preferences/ folder. But this also encores the policy on the Dev and Beta version of Chrome installed on the same MacBook. I tried creating com.google.Chrome.beta.plist and com.google.Chrome.dev.plist files but it does not seem to work and it fetches the policy from the main plist file (stable) and applies it for all versions of Chrome.

How can I apply separate policies for difference Chrome versions?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>IncognitoModeAvailability</key>
    <integer>2</integer>
</dict>
</plist>
```

**Applicable Documentation URL(s)**: *If applicable ...*

**How are you testing / deploying your profile?**: *ex. manual profile install, MDM, etc.*

**Comment by relgit** [comment]
Looks like this thread did not yield any answers to the question, so I'm going to close it. If you didn't manage so far to find an answer elsewhere, a good place to ask would be the `#chrome` channel on Mac Admins Slack. Good luck!
