### ISSUE TITLE
Update Skype payload with new keys and titles.

### ISSUE THREAD

**Issue by erikberglund** [erikberglund/ProfileManifests#70]
The keys for the Skype payload can be confusing. Consider adding an inverted boolean and a proper title to make them work the same. Or just make it more clear what true or false actually is setting.

After a quick googling, the following keys have also been mentioned for com.skype.skype. But I have no idea if they work in this version or if they are for older versions:

- SKDisableWelcomeTour
- SKShowSilentUpgradeNotice
- SKShowWelcomeTour
- SKShowWelcomeOnLogin
- SKSilentUpgradeNoticeScreen
- SKShowSplash
- DialpadOpen

**Comment by apizz** [comment]
https://techcommunity.microsoft.com/t5/Skype-for-Business-IT-Pro/Skype-for-Business-Mac-client-Preference-Settings/td-p/66530

**Comment by apizz** [comment]
Official documentation here: https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/customize-the-mac-client-experience
