### ISSUE TITLE
Add new Certificate Transparency Payload (com.apple.security.certificatetransparency)

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileManifests#88]
https://support.apple.com/guide/mdm/certificate-transparency-mdmbafaa79ff/1/web/1

https://support.apple.com/en-us/HT205280

https://support.apple.com/guide/mdm/certificate-transparency-custom-payload-mdmd0d176513/1/web/1

**Comment by erikberglund** [comment]
Was there an update to this payload that's missing in the one currently in ProfileCreator?

**Comment by apizz** [comment]
My apologies.  I didn't look at this one closely enough.  It's _new for Jamf_, not for PC.

**Comment by erikberglund** [comment]
No worries, I'm not that good at keeping track of these changes to payloads so I'm glad you do :)
