### ISSUE TITLE
Update Skype for Business Manifest

### ISSUE THREAD

**Issue by golbiga** [erikberglund/ProfileManifests#92]
AutoDetectAutoDicoveryURLs needs to be set to autoDetectAutoDicoveryURLs. The app will ignore the setting otherwise.

**Comment by apizz** [comment]
Despite [Microsoft's Documentation](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/customize-the-mac-client-experience) saying it is `AutoDetectAutoDicoveryURLs`, all other preference keys listed all start with a lowercase letter.  So very likely a typo.

smh ...

**Comment by apizz** [comment]
Completed per https://github.com/erikberglund/ProfileManifests/commit/693ea63d5eea10c46636aade189f34a0646d5c66
