### ISSUE TITLE
Core Services UI Agent key misspelling

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileManifests#93]
Was testing a Mojave machine today and setting `CSUIDisable32BitWarning` to `true`, but prompts persisted.

Checked on rtrouton blog and found this same preference, with an added **s**: https://github.com/rtrouton/profiles/commit/d436ea1e052675dcdf04522d0467dfea6e74dae5

Since pushing this via MCX profile in MDM haven't seen prompt, so I think it's safe to say it's supposed to be `CSUIDisable32BitWarnings`

**Comment by erikberglund** [comment]
Yeah. https://support.apple.com/es-us/HT209028
