### ISSUE TITLE
ManagedInstalls LicenseInfoURL

### ISSUE THREAD

**Issue by ScarabMonkey** [erikberglund/ProfileManifests#94]
Please add a field for LicenseInfoURL in ManagedInstalls (Munki) as described here:
https://github.com/munki/munki/wiki/License-Seat-Tracking

**Comment by apizz** [comment]
@ScarabMonkey unclear as to the request.  I see the License Seat Tracking, but from my understanding this is part of pkginfo files, not the primary munki config that can be created in ProfileCreator.

**Comment by apizz** [comment]
My apologies, I read too quickly.  I see `LicenseInfoURL` ....

**Comment by erikberglund** [comment]
This is now added and available in the app if you update the manifests. Normally it's done by default on each launch, if not then go to Preferences -> Payloads and click Updated Now then Download.
